app.nome=VetApp PROD

# Servidor
spring.application.name=vetAppDalen
server.port=${PORT:8080}
logging.level.root=INFO

app.db.name=PostgreSQL

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql:///vetapp-db?cloudSqlInstance=vetappdalen:southamerica-east1:vetapp-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false