app.nome=VetApp PROD

# Servidor
spring.application.name=vetAppDalen
server.port=${PORT:8080}
logging.level.root=INFO

app.db.name=PostgreSQL


spring.datasource.url=jdbc:postgresql:///vetapp-db?cloudSqlInstance=vetappdalen:southamerica-east1:vetapp-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=vetapp_user
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool (IMPORTANTE em Cloud Run)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=20000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Startup resiliente
spring.sql.init.mode=never