name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Definir projeto
        run: gcloud config set project vetappdalen

      # Definir ambiente dinamicamente
      - name: Definir variáveis
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "SERVICE=vetapp" >> $GITHUB_ENV
            echo "ENV=prod" >> $GITHUB_ENV
          else
            echo "SERVICE=vetapp-dev" >> $GITHUB_ENV
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      # Build versionado
      - name: Build da imagem
        run: |
          IMAGE=gcr.io/vetappdalen/vetapp
          TAG=${{ github.sha }}

          gcloud builds submit . --tag $IMAGE:$TAG

          gcloud container images add-tag \
            $IMAGE:$TAG \
            $IMAGE:latest \
            --quiet

      # Deploy
      - name: Deploy no Cloud Run
        run: >
          gcloud run deploy $SERVICE
          --image gcr.io/vetappdalen/vetapp:${{ github.sha }}
          --platform managed
          --region southamerica-east1
          --allow-unauthenticated
          --set-env-vars SPRING_PROFILES_ACTIVE=prod
          --set-secrets DB_PASSWORD=DB_PASSWORD:latest
          --add-cloudsql-instances vetappdalen:southamerica-east1:vetapp-db